# EcommerceApi Application Configuration
# Server port
server.port=8080

# Application name
spring.application.name=EcommerceApi

# Logging configuration
logging.level.org.springframework.web=INFO
logging.level.com.ws101.deleon=DEBUG